services:
  postgres:
    image: postgres:15
    container_name: wallet_postgres
    restart: always
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
