ktor:
  application:
    modules:
      - com.example.wallet.ApplicationKt.module
  deployment:
    port: 8080

db:
  url: "jdbc:postgresql://localhost:5432/walletdb"
  user: wallet_user
  password: password123